version: '3.4'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    restart: always
    working_dir: /app
    command: mlflow server -h 0.0.0.0
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000/
    volumes:
      - ./mlflow_data:/mlflow
    networks:
      - mlflow

networks:
  mlflow: